name: Runner
on:
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/workflows/tags.yml
              with:
                boolean: true
