name: Runner
on:
    push: 
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    .github
            - run: ls -lh
            - name: Upload artifacts
              uses: ./.github/workflows/tags.yml 

