name: Runner
on:
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    .github
                    src
            - run: ls -lhR ../
            - name: Upload artifacts
              uses: ./.github/workflows/tags.yml 

