name: Runner
on:
    push: 
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Check
              env: 
                  env.DISTR_DIR: $PWD
              shell: pwsh
              run: |
                new-item -name ${{ env.DISTR_DIR }}\123.msi -itemtype file -force
                if (!(Test-Path ${{ env.DISTR_DIR }}\123.msi)) { 
                Write-Output "::error ::ECDIS distro files are mising." 
                exit 1 }
                

