name: Runner
on:
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - run: ls -lhR 
            - name: Upload artifacts
              uses: ./.github/workflows/tags.yml 

