name: Runner
on:
    push: 
    workflow_dispatch: 
jobs:
    run_tags:
        name: run_tags
        runs-on: mytestubuntu3
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Check
              env: 
                  DISTR_DIR: $PWD
              shell: pwsh
              run: |
                new-item -name 123.msp -path ${{ env.DISTR_DIR }} -itemtype file -force
                if (!(Test-Path "${{ env.DISTR_DIR }}\*.msi")) { 
                Write-Output "::error ::ECDIS distro files are mising." 
                exit 1 }
                else {
                write-output "ok"
                }

