name: Upload artifacts
on:
  # push: 
  #   tags:
  #     - 'version-\d\.\\d{2}\.\\d{4}.0'
  # workflow_dispatch:
  workflow_call: 
    inputs:
      boolean:
        default: false
        type: boolean
        required: false

# permissions: 
#   contents: 
#     read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set env
        shell: bash
        run:  |
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1 --branches=master`)
          latestVer=${latestTag#*-}
          echo "RELEASE_VERSION=$latestVer" >> $GITHUB_ENV
      - name: Create 
        # if: ${{ endsWith(github.event.ref, '0') }}
        if: inputs.boolean == true
        run: |
            sudo ls -lh
            echo "My Path $PWD"
            echo $GITHUB_ACTION_REPOSITORY
            echo $GITHUB_CONTEXT
            #echo "Mytag ended with 0"
            # azcopy copy "./src/*" \
            #   "https://storageazcopytest001.blob.core.windows.net/artifacts/main?${{ secrets.AZURE_STORAGE_KEY }}" 
