name: Upload artifacts
on:
  push: 
    tags:
      - 'version\d\.\d{2}\.\d{4}\.0'
  workflow_dispatch:
permissions: 
  contents: 
    read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref:
          fetch-depth: 0
      - name: Set env
        shell: bash
        run:  |
          latestTag=$(git describe --tags `git rev-list --tags --max-count=1 --branches=master`)
          latestVer=${latestTag#*-}
          echo "RELEASE_VERSION=$latestVer" >> $GITHUB_ENV
      - name: Create 
        # if: ${{ endsWith(github.event.ref, '.0') }}
        run: |
            sudo ls -lh
            echo "My Path $PWD"
            # echo $GITHUB_ACTION_REPOSITORY
            # echo $GITHUB_CONTEXT
            #echo "Mytag ended with 0"
      - name: Dump github context
        run:   echo "$GITHUB_CONTEXT"
        shell: bash
        env:
         GITHUB_CONTEXT: ${{ toJson(github) }}
